### ISSUE TITLE
Introduce more configuration options

### ISSUE THREAD

**Issue by olegbespalov** [grafana/xk6-output-opentelemetry#7]
# What?

In #5, we align the configuration with the OpenTelemetry SDK. Based on this, we should also introduce more configuration options, like:

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-output-opentelemetry/pull/11
- [ ] Support for TLS configuration
- [ ] Support for passing the headers (metadata in gRPC)
```

# Why?

Having configurable output should cover many cases that our users could have.
